"use client";

import { ChangeEvent, CSSProperties, useEffect, useMemo, useRef, useState } from "react";

type WorkflowStep = "brand" | "references" | "generate" | "review" | "deliver";
type Section = "projects" | "library" | "settings";
type AssetFile = { id: string; name: string; url: string; raw: string };
type Material = { id: string; name: string; description: string; referenceName?: string; referenceUrl?: string };
type Ratios = { black: number; white: number; brand: number; auxiliary: number };

const steps: { id: WorkflowStep; label: string }[] = [
  { id: "brand", label: "导入资产" }, { id: "references", label: "确认资产" }, { id: "generate", label: "延展规则" }, { id: "review", label: "生成与调整" }, { id: "deliver", label: "矢量导出" },
];
const defaultMaterials: Material[] = [
  { id: "card", name: "名片", description: "" }, { id: "bag", name: "手提袋", description: "" }, { id: "box", name: "包装盒", description: "" },
];
const extensionOptions = ["等比放大", "超大裁切", "局部裁切", "完整展示", "少量重复", "图形拆解", "局部元素提取", "负形利用", "黑白反白", "允许旋转", "连续构图"];
const boundaryOptions = ["不重新设计 Logo", "不改变路径形状", "不增加无关装饰图形", "不使用光效 / 粒子 / 纹理", "不使用阴影", "不使用 3D / 透视", "不使用摄影 Mockup", "保持纯二维正视图"];

function normalizeHex(x:string){ const s=x.toUpperCase(); if(/^#[0-9A-F]{6}$/.test(s)) return s; if(/^#[0-9A-F]{3}$/.test(s)) return `#${s[1]}${s[1]}${s[2]}${s[2]}${s[3]}${s[3]}`; return null; }
function extractSvgColors(raw:string){
  const matches=[...raw.matchAll(/(?:fill|stroke)=["'](#[0-9a-fA-F]{3,6})["']/g)].map(m=>normalizeHex(m[1])).filter(Boolean) as string[];
  const style=[...raw.matchAll(/(?:fill|stroke)\s*:\s*(#[0-9a-fA-F]{3,6})/g)].map(m=>normalizeHex(m[1])).filter(Boolean) as string[];
  const all=[...matches,...style].filter(x=>!['#000000','#FFFFFF'].includes(x));
  const counts=new Map<string,number>(); all.forEach(x=>counts.set(x,(counts.get(x)||0)+1));
  return [...counts.entries()].sort((a,b)=>b[1]-a[1]).map(x=>x[0]);
}
function makeAsset(file:File, raw:string):AssetFile { return {id:`${Date.now()}-${Math.random()}`,name:file.name,url:URL.createObjectURL(file),raw}; }

export function WorkspaceShell(){
  const [section,setSection]=useState<Section>("projects"); const [started,setStarted]=useState(false); const [step,setStep]=useState<WorkflowStep>("brand"); const [dark,setDark]=useState(true);
  const [graphic,setGraphic]=useState<AssetFile|null>(null); const [cnTexts,setCnTexts]=useState<AssetFile[]>([]); const [enTexts,setEnTexts]=useState<AssetFile[]>([]);
  const [brandColor,setBrandColor]=useState("#008FDB"); const [auxiliaryColors,setAuxiliaryColors]=useState<string[]>([]); const [assetsConfirmed,setAssetsConfirmed]=useState(false);
  const [selectedExtensions,setSelectedExtensions]=useState<string[]>(["超大裁切","局部裁切","完整展示","黑白反白","图形拆解"]); const [selectedBoundaries,setSelectedBoundaries]=useState<string[]>(boundaryOptions);
  const [ratios,setRatios]=useState<Ratios>({black:20,white:45,brand:30,auxiliary:5}); const [materials,setMaterials]=useState<Material[]>(defaultMaterials); const [rulesConfirmed,setRulesConfirmed]=useState(false);
  const [generated,setGenerated]=useState(false); const [generating,setGenerating]=useState(false); const [approved,setApproved]=useState<string[]>([]); const [deleted,setDeleted]=useState<string[]>([]);
  useEffect(()=>{ if(!graphic) return; const colors=extractSvgColors(graphic.raw); if(colors.length){ setBrandColor(colors[0]); setAuxiliaryColors(colors.slice(1,5)); } },[graphic]);
  const stepIndex=steps.findIndex(x=>x.id===step); const move=(d:1|-1)=>setStep(steps[Math.max(0,Math.min(4,stepIndex+d))].id);
  const canContinue=useMemo(()=> step==="brand"?!!graphic:step==="references"?assetsConfirmed:step==="generate"?(rulesConfirmed&&materials.length>0):step==="review"?(generated&&approved.length>0):true,[step,graphic,assetsConfirmed,rulesConfirmed,materials.length,generated,approved.length]);
  if(!started) return <Home section={section} setSection={setSection} dark={dark} setDark={setDark} onStart={()=>setStarted(true)}/>;
  return <main className={`shell ${dark?"dark":""}`}><Sidebar section={section} setSection={setSection} dark={dark} setDark={setDark} onHome={()=>setStarted(false)}/><section className="workflow">
    <header className="topbar"><div><button className="crumb" onClick={()=>setStarted(false)}>项目</button><span> / 当前品牌方向</span></div><div className="step-count">第 {stepIndex+1} 步，共 5 步</div></header><div className="progress"><span style={{width:`${((stepIndex+1)/5)*100}%`}}/></div>
    <div className="stepper">{steps.map((x,i)=><button key={x.id} className={i<=stepIndex?"active":""} onClick={()=>i<=stepIndex&&setStep(x.id)}><i>{i+1}</i>{x.label}</button>)}</div>
    <div className="content">
      {step==="brand"&&<ImportAssets graphic={graphic} setGraphic={setGraphic} cnTexts={cnTexts} setCnTexts={setCnTexts} enTexts={enTexts} setEnTexts={setEnTexts}/>} 
      {step==="references"&&<ConfirmAssets graphic={graphic} cnTexts={cnTexts} enTexts={enTexts} brandColor={brandColor} setBrandColor={setBrandColor} auxiliaryColors={auxiliaryColors} setAuxiliaryColors={setAuxiliaryColors} confirmed={assetsConfirmed} setConfirmed={setAssetsConfirmed}/>} 
      {step==="generate"&&<Rules selectedExtensions={selectedExtensions} setSelectedExtensions={setSelectedExtensions} selectedBoundaries={selectedBoundaries} setSelectedBoundaries={setSelectedBoundaries} ratios={ratios} setRatios={setRatios} brandColor={brandColor} auxiliaryColors={auxiliaryColors} materials={materials} setMaterials={setMaterials} confirmed={rulesConfirmed} setConfirmed={setRulesConfirmed}/>} 
      {step==="review"&&<GenerateAndReview graphic={graphic} brandColor={brandColor} materials={materials} selectedExtensions={selectedExtensions} approved={approved} setApproved={setApproved} deleted={deleted} setDeleted={setDeleted} generating={generating} setGenerating={setGenerating} generated={generated} setGenerated={setGenerated}/>} 
      {step==="deliver"&&<ExportVectors graphic={graphic} brandColor={brandColor} materials={materials} approved={approved}/>} 
    </div>
    <footer className="footer"><button className="text-btn" disabled={stepIndex===0} onClick={()=>move(-1)}>← 返回</button><button className="primary footer-primary" disabled={!canContinue} onClick={()=>stepIndex<4&&move(1)}>{stepIndex===4?"已到导出步骤":"继续 →"}</button></footer>
  </section></main>;
}

function Sidebar({section,setSection,dark,setDark,onHome}:{section:Section;setSection:(x:Section)=>void;dark:boolean;setDark:(x:boolean)=>void;onHome:()=>void}){ const names:Record<Section,string>={projects:"项目",library:"资料库",settings:"设置"}; return <aside className="sidebar"><button className="mark mark-btn" onClick={onHome}>DI</button><nav>{(["projects","library","settings"] as const).map(x=><button key={x} className={section===x?"nav-on":""} onClick={()=>{setSection(x);onHome();}}>{names[x]}</button>)}</nav><button className="theme-toggle" onClick={()=>setDark(!dark)}><span>{dark?"☀":"☾"}</span>{dark?"日间":"黑夜"}</button></aside>; }
function Home({section,setSection,dark,setDark,onStart}:{section:Section;setSection:(x:Section)=>void;dark:boolean;setDark:(x:boolean)=>void;onStart:()=>void}){ return <main className={`shell ${dark?"dark":""}`}><Sidebar section={section} setSection={setSection} dark={dark} setDark={setDark} onHome={()=>setSection("projects")}/><section className="home">{section==="projects"&&<><p className="eyebrow">Design Intelligence Workspace</p><h1>用一个确定的 Logo，快速试出一整套品牌氛围。</h1><p className="muted home-intro">上传图形与文字资产，选择延展方式和物料，让工作台快速生成提案级二维品牌应用。</p><button className="continue-card" onClick={onStart}><div><span>当前项目</span><h2>新品牌方向</h2><p>等待导入 Logo 图形</p></div><b>开始 →</b></button><div className="heading-row"><h3>最近项目</h3><button className="text-btn" onClick={onStart}>+ 新建项目</button></div><div className="empty-projects">最近项目会在保存后出现在这里。</div></>}{section==="library"&&<Library/>}{section==="settings"&&<Settings/>}</section></main>; }

function SingleAsset({title,hint,asset,required,onChange}:{title:string;hint:string;asset:AssetFile|null;required?:boolean;onChange:(x:AssetFile)=>void}){ const ref=useRef<HTMLInputElement>(null); const load=async(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;if(!f.name.toLowerCase().endsWith('.svg')){alert('当前版本仅支持 SVG 矢量文件。');return;}onChange(makeAsset(f,await f.text()));e.target.value='';}; return <div className="asset-upload"><input ref={ref} hidden type="file" accept=".svg,image/svg+xml" onChange={load}/><div className="asset-upload-preview white-preview">{asset?<img src={asset.url} alt=""/>:<span>SVG</span>}</div><div><div className="asset-title-row"><b>{title}</b>{required&&<em>必填</em>}</div><p>{asset?asset.name:hint}</p></div><button className="secondary" onClick={()=>ref.current?.click()}>{asset?"重新选择":"选择文件"}</button></div>; }
function MultiAssets({title,hint,assets,setAssets}:{title:string;hint:string;assets:AssetFile[];setAssets:(x:AssetFile[])=>void}){ const ref=useRef<HTMLInputElement>(null); const load=async(e:ChangeEvent<HTMLInputElement>)=>{const files=[...(e.target.files||[])]; const valid=files.filter(f=>f.name.toLowerCase().endsWith('.svg')); const loaded=await Promise.all(valid.map(async f=>makeAsset(f,await f.text()))); setAssets([...assets,...loaded]);e.target.value='';}; return <div className="multi-upload"><div className="multi-upload-head"><div><b>{title}</b><p>{hint}</p></div><button className="secondary" onClick={()=>ref.current?.click()}>+ 添加版式</button><input ref={ref} hidden multiple type="file" accept=".svg,image/svg+xml" onChange={load}/></div>{assets.length?<div className="variant-grid">{assets.map((a,i)=><div className="variant-card" key={a.id}><div className="white-preview"><img src={a.url} alt=""/></div><span>版式 {i+1}</span><small>{a.name}</small><button onClick={()=>setAssets(assets.filter(x=>x.id!==a.id))}>删除</button></div>)}</div>:<div className="variant-empty">尚未提供，可跳过。</div>}</div>; }
function ImportAssets({graphic,setGraphic,cnTexts,setCnTexts,enTexts,setEnTexts}:{graphic:AssetFile|null;setGraphic:(x:AssetFile)=>void;cnTexts:AssetFile[];setCnTexts:(x:AssetFile[])=>void;enTexts:AssetFile[];setEnTexts:(x:AssetFile[])=>void}){ return <div className="single wide-single"><p className="eyebrow">第 1 步 · 导入资产</p><h1>先把 Logo 图形和文字版式交给工作台。</h1><p className="muted">Logo 图形必填；中文和英文可以各自上传多个既定版式，例如单行、两行。每一个版式都会成为后续 AI 可调用的品牌资产。</p><div className="asset-upload-stack"><SingleAsset title="Logo 图形" hint="上传定稿图形主体 SVG" required asset={graphic} onChange={setGraphic}/><MultiAssets title="中文文字版式" hint="可选 · 支持多个版式" assets={cnTexts} setAssets={setCnTexts}/><MultiAssets title="英文文字版式" hint="可选 · 支持多个版式" assets={enTexts} setAssets={setEnTexts}/></div></div>; }

function PreviewCard({title,asset}:{title:string;asset:AssetFile|null}){return <div className="asset-preview-card"><span>{title}</span><div className="white-preview">{asset?<img src={asset.url} alt=""/>:<small>未提供</small>}</div><b>{asset?.name||"—"}</b></div>}
function VariantPreview({title,assets}:{title:string;assets:AssetFile[]}){return <div className="asset-preview-card multi-preview"><span>{title}</span><div className="preview-variants">{assets.length?assets.map((a,i)=><div className="white-preview" key={a.id}><img src={a.url} alt=""/><small>{i+1}</small></div>):<div className="white-preview"><small>未提供</small></div>}</div><b>{assets.length?`${assets.length} 个可用版式`:"—"}</b></div>}
function ColorEditor({color,onChange,onRemove,locked}:{color:string;onChange:(x:string)=>void;onRemove?:()=>void;locked?:boolean}){return <div className="color-editor"><input type="color" value={color} onChange={e=>onChange(e.target.value.toUpperCase())}/><input value={color} onChange={e=>{const x=e.target.value.toUpperCase();if(/^#[0-9A-F]{0,6}$/.test(x))onChange(x)}}/>{!locked&&onRemove&&<button onClick={onRemove}>×</button>}</div>}
function ConfirmAssets({graphic,cnTexts,enTexts,brandColor,setBrandColor,auxiliaryColors,setAuxiliaryColors,confirmed,setConfirmed}:{graphic:AssetFile|null;cnTexts:AssetFile[];enTexts:AssetFile[];brandColor:string;setBrandColor:(x:string)=>void;auxiliaryColors:string[];setAuxiliaryColors:(x:string[])=>void;confirmed:boolean;setConfirmed:(x:boolean)=>void}){ const addAux=()=>setAuxiliaryColors([...auxiliaryColors,"#B8B8B8"]); return <div className="single wide-single"><p className="eyebrow">第 2 步 · 确认资产</p><h1>确认后面允许使用的品牌原料。</h1><p className="muted">工作台会先从 Logo SVG 中读取颜色作为建议值；你仍然可以手动修改主色，并添加多个辅助色。</p><div className="asset-confirm-grid"><PreviewCard title="Logo 图形" asset={graphic}/><VariantPreview title="中文版式" assets={cnTexts}/><VariantPreview title="英文版式" assets={enTexts}/></div><section className="color-panel"><div className="color-panel-head"><div><span>品牌主色</span><small>已尝试从 Logo SVG 自动识别</small></div></div><ColorEditor color={brandColor} onChange={setBrandColor} locked/><div className="color-panel-head aux-head"><div><span>辅助色</span><small>可多选 · 后续作为 AI 可调用色板</small></div><button className="secondary" onClick={addAux}>+ 添加辅助色</button></div><div className="aux-list">{auxiliaryColors.length?auxiliaryColors.map((c,i)=><ColorEditor key={`${c}-${i}`} color={c} onChange={x=>setAuxiliaryColors(auxiliaryColors.map((v,j)=>j===i?x:v))} onRemove={()=>setAuxiliaryColors(auxiliaryColors.filter((_,j)=>j!==i))}/>):<small>未识别到其它颜色，可按需添加。</small>}</div></section><label className="confirm-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>确认：后续 AI 只使用上述 Logo、文字版式与色板，不重新设计 Logo。</span></label></div>; }

function ToggleChips({options,selected,setSelected}:{options:string[];selected:string[];setSelected:(x:string[])=>void}){const toggle=(x:string)=>setSelected(selected.includes(x)?selected.filter(y=>y!==x):[...selected,x]);return <div className="choice-grid">{options.map(x=><button key={x} className={selected.includes(x)?"selected":""} onClick={()=>toggle(x)}>{selected.includes(x)?"✓ ":"+ "}{x}</button>)}</div>}
function ColorRatio({ratios,setRatios,brandColor,auxiliaryColors}:{ratios:Ratios;setRatios:(x:Ratios)=>void;brandColor:string;auxiliaryColors:string[]}){ const entries:[keyof Ratios,string,string][]=[["black","黑色","#111111"],["white","白色","#FFFFFF"],["brand","品牌主色",brandColor],["auxiliary","辅助色",auxiliaryColors[0]||"#B8B8B8"]]; const total=Object.values(ratios).reduce((a,b)=>a+b,0)||1; return <div><div className="ratio-bar">{entries.map(([k,,c])=><i key={k} style={{width:`${(ratios[k]/total)*100}%`,background:c}}/>)}</div><div className="ratio-controls">{entries.map(([k,label,c])=><label key={k}><span><i style={{background:c}}/>{label}<b>{ratios[k]}%</b></span><input type="range" min="0" max="100" value={ratios[k]} onChange={e=>setRatios({...ratios,[k]:Number(e.target.value)})}/></label>)}</div><p>比例是视觉倾向，不是硬性像素占比；后续会作为 AI 的配色权重指令。</p></div> }
function Rules({selectedExtensions,setSelectedExtensions,selectedBoundaries,setSelectedBoundaries,ratios,setRatios,brandColor,auxiliaryColors,materials,setMaterials,confirmed,setConfirmed}:{selectedExtensions:string[];setSelectedExtensions:(x:string[])=>void;selectedBoundaries:string[];setSelectedBoundaries:(x:string[])=>void;ratios:Ratios;setRatios:(x:Ratios)=>void;brandColor:string;auxiliaryColors:string[];materials:Material[];setMaterials:(x:Material[])=>void;confirmed:boolean;setConfirmed:(x:boolean)=>void}){ const update=(id:string,p:Partial<Material>)=>setMaterials(materials.map(m=>m.id===id?{...m,...p}:m)); const add=()=>setMaterials([...materials,{id:`custom-${Date.now()}`,name:"新物料",description:""}]); const refInput=(id:string,e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(f)update(id,{referenceName:f.name,referenceUrl:URL.createObjectURL(f)})}; return <div className="rules-page"><p className="eyebrow">第 3 步 · 延展规则</p><h1>把你的判断变成 AI 的设计指令。</h1><p className="muted">前端只是把复杂 Prompt 变成简单选择题；真正生成时，所有选项、比例、描述和参考图都会一起进入 AI 指令。</p><section className="rule-card"><span className="rule-tag">Logo 延展方式 · 多选</span><ToggleChips options={extensionOptions} selected={selectedExtensions} setSelected={setSelectedExtensions}/></section><section className="rule-card"><span className="rule-tag">颜色使用倾向</span><ColorRatio ratios={ratios} setRatios={setRatios} brandColor={brandColor} auxiliaryColors={auxiliaryColors}/></section><section className="rule-card"><span className="rule-tag">视觉边界 · 多选</span><ToggleChips options={boundaryOptions} selected={selectedBoundaries} setSelected={setSelectedBoundaries}/></section><section className="rule-card"><div className="rule-head"><div><span className="rule-tag">首轮物料</span><h3>告诉 AI 这次要做什么。</h3></div><button className="secondary" onClick={add}>+ 新增物料</button></div><div className="material-editor-list">{materials.map((m,index)=><div className="material-editor" key={m.id}><div className="material-number">{String(index+1).padStart(2,"0")}</div><div className="material-fields"><input value={m.name} onChange={e=>update(m.id,{name:e.target.value})}/><textarea value={m.description} onChange={e=>update(m.id,{description:e.target.value})} placeholder="设计描述（选填）。没有描述时由 AI 自由发挥。"/><label className="reference-upload"><input type="file" accept="image/*" hidden onChange={e=>refInput(m.id,e)}/>{m.referenceName?`参考图：${m.referenceName}`:"+ 上传参考图（选填）"}</label></div><button className="remove-btn" onClick={()=>setMaterials(materials.filter(x=>x.id!==m.id))}>删除</button></div>)}</div></section><label className="confirm-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>使用以上选择作为本轮 AI 生成指令。</span></label></div>; }

function GenerateAndReview({graphic,brandColor,materials,selectedExtensions,approved,setApproved,deleted,setDeleted,generating,setGenerating,generated,setGenerated}:{graphic:AssetFile|null;brandColor:string;materials:Material[];selectedExtensions:string[];approved:string[];setApproved:(x:string[])=>void;deleted:string[];setDeleted:(x:string[])=>void;generating:boolean;setGenerating:(x:boolean)=>void;generated:boolean;setGenerated:(x:boolean)=>void}){ const visible=materials.filter(m=>!deleted.includes(m.id)); const generate=()=>{setGenerating(true);setTimeout(()=>{setGenerating(false);setGenerated(true)},1000)}; const keep=(id:string)=>setApproved(approved.includes(id)?approved.filter(x=>x!==id):[...approved,id]); const remove=(id:string)=>{setDeleted([...deleted,id]);setApproved(approved.filter(x=>x!==id));}; return <div className="review-page"><p className="eyebrow">第 4 步 · 生成与调整</p><h1>{generated?"第一轮结果出来了，保留好的，删掉坏的。":"生成第一轮品牌应用。"}</h1><p className="muted">只有明确点击“保留”的方案才会进入第 5 步。删除代表这一版明确淘汰。</p>{!generated&&<button className="primary large generate-btn" onClick={generate} disabled={generating}>{generating?"生成中…":"生成第一轮"}</button>}{generated&&<><div className="result-list">{visible.map((m,i)=><article className="result-card" key={m.id}><div className={`result-art result-${i%3}`} style={{"--brand":brandColor} as CSSProperties}><div className="result-svg-preview white-preview">{graphic&&<img src={graphic.url} alt=""/>}</div><small>{m.name}</small></div><div className="result-meta"><b>{m.name}</b><span>{m.description||`AI 自由发挥 · ${selectedExtensions.slice(0,3).join(" / ")}`}</span><div><button className={approved.includes(m.id)?"approved":""} onClick={()=>keep(m.id)}>{approved.includes(m.id)?"已保留 ✓":"保留"}</button><button>调整</button><button onClick={()=>setGenerated(false)}>重做</button><button className="danger-btn" onClick={()=>remove(m.id)}>删除</button></div></div></article>)}</div>{deleted.length>0&&<div className="deleted-note">已删除 {deleted.length} 个方案。重新生成整轮可恢复。</div>}</>}</div>; }

function ExportVectors({graphic,brandColor,materials,approved}:{graphic:AssetFile|null;brandColor:string;materials:Material[];approved:string[]}){ const targets=materials.filter(m=>approved.includes(m.id)); const download=(m:Material,index:number)=>{const inner=graphic?.raw.replace(/<\?xml[^>]*>/g,"")||"";const body=inner.replace(/<svg([^>]*)>/i,"<g>").replace(/<\/svg>/i,"</g>");const bg=index%3===0?"#111111":index%3===1?"#FFFFFF":brandColor;const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="800" viewBox="0 0 1200 800"><rect width="1200" height="800" fill="${bg}"/><g transform="translate(620 120) scale(2.2)">${body}</g></svg>`;const blob=new Blob([svg],{type:"image/svg+xml"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`${m.name}.svg`;a.click();URL.revokeObjectURL(url)}; return <div className="single wide-single"><p className="eyebrow">第 5 步 · 矢量导出</p><h1>这里只留下你明确保留的方案。</h1><p className="muted">未点击保留、已经删除的方案都不会进入导出。</p><div className="export-list">{targets.map((m,i)=><div key={m.id}><div className="export-preview white-preview">{graphic&&<img src={graphic.url} alt=""/>}</div><div><b>{m.name}</b><span>SVG · 原始 Logo 路径保留</span></div><button className="secondary" onClick={()=>download(m,i)}>导出 SVG</button></div>)}</div></div>; }
function Library(){return <><p className="eyebrow">资料库</p><h1>参考与历史资产。</h1><p className="muted">后续保存 Logo、文字版式、色板、参考图和成功规则。</p><div className="empty-projects">当前还没有保存的资料。</div></>}
function Settings(){return <><p className="eyebrow">设置</p><h1>工作台设置。</h1><p className="muted">下一阶段配置 OpenAI API Key、本地存储和默认输出规则。</p><div className="settings-placeholder"><b>OpenAI API</b><span>尚未配置</span><button className="secondary">稍后接入</button></div></>}
